require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colourscheme"

require "user.nvim-tree"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.alpha"
